name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger on tags in the format v1.2.3
    branches:
      - main      # Trigger only when pushing to the main branch

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Add your release notes here
          draft: false
          prerelease: false

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            !composer.lock
            !composer.json
            !.gitignore
          asset_name: asset_filename.ext
          asset_content_type: application/octet-stream
